# Generated by Django 3.2.5 on 2021-07-31 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessInput',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('value', models.CharField(max_length=360)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessOutput',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('value', models.CharField(max_length=360)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('serverName', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('dbName', models.CharField(max_length=60)),
                ('dbServerName', models.CharField(max_length=60)),
                ('serverIp', models.GenericIPAddressField()),
                ('version', models.CharField(max_length=60)),
                ('loginUrl', models.CharField(max_length=500)),
                ('releasesUrl', models.CharField(max_length=500)),
                ('startJobUrl', models.CharField(max_length=500)),
                ('getJobsUrl', models.CharField(max_length=500)),
                ('status', models.BooleanField(default=False)),
                ('lastRestartTime', models.DateTimeField(auto_now=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('userName', models.CharField(max_length=120)),
                ('password', models.CharField(max_length=120)),
                ('orchUserName', models.CharField(max_length=120)),
                ('orchPassword', models.CharField(max_length=120)),
                ('dbUserName', models.CharField(max_length=120)),
                ('dbPassword', models.CharField(max_length=120)),
                ('uiPathFilePath', models.CharField(max_length=500)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uipath_server_created_by', to=settings.AUTH_USER_MODEL)),
                ('lastEditedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uipath_server_last_edited_by', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uipath_server_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('triggerName', models.CharField(max_length=360)),
                ('releaseKey', models.CharField(max_length=360)),
                ('processName', models.CharField(max_length=60)),
                ('tenancyName', models.CharField(max_length=60)),
                ('processInputs', models.ManyToManyField(blank=True, related_name='uipath_trigger_process_inputs', to='uipath.ProcessInput')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uipath_server', to='uipath.server')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('scheduleName', models.CharField(max_length=360, null=True)),
                ('status', models.CharField(blank=True, max_length=9, null=True)),
                ('userName', models.CharField(max_length=120)),
                ('recurringType', models.CharField(default='Once', max_length=30)),
                ('occurOnceDateTime', models.DateTimeField(blank=True, null=True)),
                ('recurringTime', models.TimeField(blank=True, null=True)),
                ('recurringStartDate', models.DateField(blank=True, null=True)),
                ('recurringEndDate', models.DateField(blank=True, null=True)),
                ('trigger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uipath_schedule_trigger', to='uipath.trigger')),
            ],
        ),
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('startJobKey', models.CharField(max_length=360)),
                ('endTime', models.DateTimeField(auto_now=True)),
                ('startTime', models.DateTimeField(auto_now_add=True)),
                ('executionDuration', models.DurationField(null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('processInputs', models.ManyToManyField(blank=True, related_name='uipath_execution_process_inputs', to='uipath.ProcessInput')),
                ('processOutputs', models.ManyToManyField(blank=True, related_name='uipath_execution_process_outputs', to='uipath.ProcessOutput')),
                ('schedule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='uipath.schedule')),
            ],
        ),
    ]
