# Generated by Django 3.2.5 on 2021-08-08 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ae', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processoutput',
            name='value',
            field=models.CharField(max_length=2000),
        ),
    ]
