# Generated by Django 3.2.5 on 2021-08-15 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ae', '0003_auto_20210815_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='execution',
            name='trigger',
        ),
        migrations.AddField(
            model_name='execution',
            name='schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ae.schedule'),
            preserve_default=False,
        ),
    ]
