# Generated by Django 3.2.5 on 2021-07-31 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessInput',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('value', models.CharField(max_length=360)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessOutput',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('value', models.CharField(max_length=360)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('serverName', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('dbName', models.CharField(max_length=60)),
                ('dbServerName', models.CharField(max_length=60)),
                ('serverIp', models.GenericIPAddressField()),
                ('aeVersion', models.CharField(max_length=60)),
                ('listenerUrl', models.CharField(max_length=60)),
                ('aeSiteUrl', models.CharField(max_length=60)),
                ('messagingUrl', models.CharField(max_length=60)),
                ('status', models.BooleanField(default=False)),
                ('lastRestartTime', models.DateTimeField(auto_now=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('aeSite', models.BooleanField(default=False)),
                ('messaging', models.BooleanField(default=False)),
                ('listener', models.BooleanField(default=False)),
                ('controlTower', models.BooleanField(default=False)),
                ('etl', models.BooleanField(default=False)),
                ('vanguard', models.BooleanField(default=False)),
                ('userName', models.CharField(max_length=120)),
                ('password', models.CharField(max_length=120)),
                ('aeFilePath', models.CharField(max_length=500)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ae_server_created_by', to=settings.AUTH_USER_MODEL)),
                ('lastEditedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ae_server_last_edited_by', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ae_server_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('triggerName', models.CharField(max_length=360)),
                ('processName', models.CharField(max_length=60)),
                ('profileName', models.CharField(max_length=60)),
                ('processExpirationTime', models.IntegerField()),
                ('processInputs', models.ManyToManyField(blank=True, related_name='processInputs', to='ae.ProcessInput')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ae_server', to='ae.server')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('scheduleName', models.CharField(max_length=360, null=True)),
                ('status', models.CharField(blank=True, max_length=9, null=True)),
                ('userName', models.CharField(max_length=120)),
                ('recurringType', models.CharField(default='Once', max_length=30)),
                ('occurOnceDateTime', models.DateTimeField(blank=True, null=True)),
                ('recurringTime', models.TimeField(blank=True, null=True)),
                ('recurringStartDate', models.DateField(blank=True, null=True)),
                ('recurringEndDate', models.DateField(blank=True, null=True)),
                ('trigger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ae_schedule_trigger', to='ae.trigger')),
            ],
        ),
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message_id', models.CharField(max_length=360, null=True)),
                ('endTime', models.DateTimeField(auto_now=True)),
                ('startTime', models.DateTimeField(auto_now_add=True)),
                ('executionDuration', models.DurationField(null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('processInputs', models.ManyToManyField(blank=True, related_name='ae_execution_process_inputs', to='ae.ProcessInput')),
                ('processOutputs', models.ManyToManyField(blank=True, related_name='ae_execution_process_outputs', to='ae.ProcessOutput')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ae.schedule')),
            ],
        ),
    ]
