# Generated by Django 3.2.5 on 2021-08-19 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uipath', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='execution',
            name='schedule',
        ),
        migrations.AddField(
            model_name='execution',
            name='trigger',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='uipath.trigger'),
            preserve_default=False,
        ),
    ]
