# Generated by Django 3.2.5 on 2021-08-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='orchPassword',
            field=models.CharField(default='ankit.mishra15', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='server',
            name='orchUserName',
            field=models.CharField(default='ankit.mishra15', max_length=120),
            preserve_default=False,
        ),
    ]
